# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dispersion.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dispersion(object):
    def setupUi(self, Dispersion):
        Dispersion.setObjectName("Dispersion")
        Dispersion.resize(773, 560)
        font = QtGui.QFont()
        font.setPointSize(18)
        Dispersion.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/logo/logo.ico"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        Dispersion.setWindowIcon(icon)
        self.groupBox = QtWidgets.QGroupBox(Dispersion)
        self.groupBox.setGeometry(QtCore.QRect(20, 120, 371, 421))
        self.groupBox.setMinimumSize(QtCore.QSize(331, 0))
        font = QtGui.QFont()
        font.setPointSize(17)
        self.groupBox.setFont(font)
        self.groupBox.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox.setObjectName("groupBox")
        self.beta2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.beta2.setGeometry(QtCore.QRect(40, 60, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.beta2.setFont(font)
        self.beta2.setAlignment(QtCore.Qt.AlignCenter)
        self.beta2.setDecimals(4)
        self.beta2.setMinimum(-99.0)
        self.beta2.setSingleStep(0.1)
        self.beta2.setProperty("value", 19.01)
        self.beta2.setObjectName("beta2")
        self.beta3 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.beta3.setGeometry(QtCore.QRect(40, 100, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.beta3.setFont(font)
        self.beta3.setAlignment(QtCore.Qt.AlignCenter)
        self.beta3.setDecimals(4)
        self.beta3.setMinimum(-5.0)
        self.beta3.setMaximum(5.0)
        self.beta3.setSingleStep(0.01)
        self.beta3.setProperty("value", -0.0557)
        self.beta3.setObjectName("beta3")
        self.beta4 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.beta4.setGeometry(QtCore.QRect(40, 140, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.beta4.setFont(font)
        self.beta4.setAlignment(QtCore.Qt.AlignCenter)
        self.beta4.setDecimals(4)
        self.beta4.setMinimum(-1.0)
        self.beta4.setMaximum(1.0)
        self.beta4.setSingleStep(0.001)
        self.beta4.setProperty("value", -0.0005)
        self.beta4.setObjectName("beta4")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 60, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.groupBox_3 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_3.setGeometry(QtCore.QRect(0, 30, 181, 391))
        self.groupBox_3.setObjectName("groupBox_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(131, 30, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.groupBox_3)
        self.label_5.setGeometry(QtCore.QRect(131, 70, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox_3)
        self.label_6.setGeometry(QtCore.QRect(131, 110, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_3)
        self.label_7.setGeometry(QtCore.QRect(10, 243, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        self.label_8.setGeometry(QtCore.QRect(10, 294, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_3)
        self.label_9.setGeometry(QtCore.QRect(10, 343, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_30 = QtWidgets.QLabel(self.groupBox_3)
        self.label_30.setGeometry(QtCore.QRect(130, 240, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.label_28 = QtWidgets.QLabel(self.groupBox_3)
        self.label_28.setGeometry(QtCore.QRect(130, 340, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.groupBox_3)
        self.label_29.setGeometry(QtCore.QRect(130, 290, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.btod = QtWidgets.QPushButton(self.groupBox_3)
        self.btod.setGeometry(QtCore.QRect(60, 164, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btod.setFont(font)
        self.btod.setObjectName("btod")
        self.r_D2 = QtWidgets.QLineEdit(self.groupBox_3)
        self.r_D2.setGeometry(QtCore.QRect(40, 243, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.r_D2.setFont(font)
        self.r_D2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.r_D2.setAlignment(QtCore.Qt.AlignCenter)
        self.r_D2.setReadOnly(True)
        self.r_D2.setClearButtonEnabled(False)
        self.r_D2.setObjectName("r_D2")
        self.r_D3 = QtWidgets.QLineEdit(self.groupBox_3)
        self.r_D3.setGeometry(QtCore.QRect(39, 292, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.r_D3.setFont(font)
        self.r_D3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.r_D3.setAlignment(QtCore.Qt.AlignCenter)
        self.r_D3.setReadOnly(True)
        self.r_D3.setClearButtonEnabled(False)
        self.r_D3.setObjectName("r_D3")
        self.r_D4 = QtWidgets.QLineEdit(self.groupBox_3)
        self.r_D4.setGeometry(QtCore.QRect(40, 342, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.r_D4.setFont(font)
        self.r_D4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.r_D4.setAlignment(QtCore.Qt.AlignCenter)
        self.r_D4.setReadOnly(True)
        self.r_D4.setClearButtonEnabled(False)
        self.r_D4.setObjectName("r_D4")
        self.groupBox_4 = QtWidgets.QGroupBox(self.groupBox)
        self.groupBox_4.setGeometry(QtCore.QRect(180, 30, 191, 391))
        self.groupBox_4.setObjectName("groupBox_4")
        self.D3 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.D3.setGeometry(QtCore.QRect(40, 70, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.D3.setFont(font)
        self.D3.setAlignment(QtCore.Qt.AlignCenter)
        self.D3.setDecimals(4)
        self.D3.setMinimum(-99.0)
        self.D3.setSingleStep(0.01)
        self.D3.setProperty("value", -0.3185)
        self.D3.setObjectName("D3")
        self.D4 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.D4.setGeometry(QtCore.QRect(40, 110, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.D4.setFont(font)
        self.D4.setAlignment(QtCore.Qt.AlignCenter)
        self.D4.setDecimals(4)
        self.D4.setMinimum(-99.0)
        self.D4.setSingleStep(0.1)
        self.D4.setProperty("value", -0.003)
        self.D4.setObjectName("D4")
        self.D2 = QtWidgets.QDoubleSpinBox(self.groupBox_4)
        self.D2.setGeometry(QtCore.QRect(40, 30, 91, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.D2.setFont(font)
        self.D2.setAlignment(QtCore.Qt.AlignCenter)
        self.D2.setDecimals(4)
        self.D2.setMinimum(-900.0)
        self.D2.setMaximum(900.0)
        self.D2.setSingleStep(0.1)
        self.D2.setProperty("value", -33.7502)
        self.D2.setObjectName("D2")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setGeometry(QtCore.QRect(10, 30, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setObjectName("label_18")
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setGeometry(QtCore.QRect(10, 70, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setGeometry(QtCore.QRect(10, 110, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.label_21 = QtWidgets.QLabel(self.groupBox_4)
        self.label_21.setGeometry(QtCore.QRect(20, 343, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setGeometry(QtCore.QRect(20, 294, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setGeometry(QtCore.QRect(20, 243, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.label_24 = QtWidgets.QLabel(self.groupBox_4)
        self.label_24.setGeometry(QtCore.QRect(140, 240, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_23 = QtWidgets.QLabel(self.groupBox_4)
        self.label_23.setGeometry(QtCore.QRect(140, 290, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_23.setFont(font)
        self.label_23.setObjectName("label_23")
        self.label_22 = QtWidgets.QLabel(self.groupBox_4)
        self.label_22.setGeometry(QtCore.QRect(140, 340, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName("label_22")
        self.label_25 = QtWidgets.QLabel(self.groupBox_4)
        self.label_25.setGeometry(QtCore.QRect(140, 30, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.groupBox_4)
        self.label_26.setGeometry(QtCore.QRect(140, 70, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.groupBox_4)
        self.label_27.setGeometry(QtCore.QRect(140, 110, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.dtob = QtWidgets.QPushButton(self.groupBox_4)
        self.dtob.setGeometry(QtCore.QRect(70, 164, 41, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.dtob.setFont(font)
        self.dtob.setObjectName("dtob")
        self.r_beta4 = QtWidgets.QLineEdit(self.groupBox_4)
        self.r_beta4.setGeometry(QtCore.QRect(51, 340, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.r_beta4.setFont(font)
        self.r_beta4.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.r_beta4.setAlignment(QtCore.Qt.AlignCenter)
        self.r_beta4.setReadOnly(True)
        self.r_beta4.setClearButtonEnabled(False)
        self.r_beta4.setObjectName("r_beta4")
        self.r_beta3 = QtWidgets.QLineEdit(self.groupBox_4)
        self.r_beta3.setGeometry(QtCore.QRect(50, 290, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.r_beta3.setFont(font)
        self.r_beta3.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.r_beta3.setAlignment(QtCore.Qt.AlignCenter)
        self.r_beta3.setReadOnly(True)
        self.r_beta3.setClearButtonEnabled(False)
        self.r_beta3.setObjectName("r_beta3")
        self.r_beta2 = QtWidgets.QLineEdit(self.groupBox_4)
        self.r_beta2.setGeometry(QtCore.QRect(51, 241, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.r_beta2.setFont(font)
        self.r_beta2.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.r_beta2.setAlignment(QtCore.Qt.AlignCenter)
        self.r_beta2.setReadOnly(True)
        self.r_beta2.setClearButtonEnabled(False)
        self.r_beta2.setObjectName("r_beta2")
        self.groupBox_3.raise_()
        self.beta2.raise_()
        self.beta3.raise_()
        self.beta4.raise_()
        self.label.raise_()
        self.label_3.raise_()
        self.label_2.raise_()
        self.groupBox_4.raise_()
        self.groupBox_2 = QtWidgets.QGroupBox(Dispersion)
        self.groupBox_2.setGeometry(QtCore.QRect(400, 30, 341, 511))
        self.groupBox_2.setAlignment(QtCore.Qt.AlignCenter)
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_36 = QtWidgets.QLabel(self.groupBox_2)
        self.label_36.setGeometry(QtCore.QRect(120, 270, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.label_34 = QtWidgets.QLabel(self.groupBox_2)
        self.label_34.setGeometry(QtCore.QRect(120, 320, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_31 = QtWidgets.QLabel(self.groupBox_2)
        self.label_31.setGeometry(QtCore.QRect(120, 370, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.label_35 = QtWidgets.QLabel(self.groupBox_2)
        self.label_35.setGeometry(QtCore.QRect(10, 273, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_33 = QtWidgets.QLabel(self.groupBox_2)
        self.label_33.setGeometry(QtCore.QRect(10, 373, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.label_32 = QtWidgets.QLabel(self.groupBox_2)
        self.label_32.setGeometry(QtCore.QRect(10, 324, 21, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_32.setFont(font)
        self.label_32.setObjectName("label_32")
        self.label_37 = QtWidgets.QLabel(self.groupBox_2)
        self.label_37.setGeometry(QtCore.QRect(180, 373, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.groupBox_2)
        self.label_38.setGeometry(QtCore.QRect(300, 320, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.label_39 = QtWidgets.QLabel(self.groupBox_2)
        self.label_39.setGeometry(QtCore.QRect(180, 324, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.label_40 = QtWidgets.QLabel(self.groupBox_2)
        self.label_40.setGeometry(QtCore.QRect(180, 273, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.groupBox_2)
        self.label_41.setGeometry(QtCore.QRect(300, 270, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.groupBox_2)
        self.label_42.setGeometry(QtCore.QRect(300, 370, 31, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.gcal = QtWidgets.QPushButton(self.groupBox_2)
        self.gcal.setGeometry(QtCore.QRect(90, 190, 151, 41))
        self.gcal.setObjectName("gcal")
        self.G = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.G.setGeometry(QtCore.QRect(130, 100, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.G.setFont(font)
        self.G.setAlignment(QtCore.Qt.AlignCenter)
        self.G.setDecimals(3)
        self.G.setMaximum(2.0)
        self.G.setSingleStep(0.001)
        self.G.setProperty("value", 0.31)
        self.G.setObjectName("G")
        self.theta_o = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.theta_o.setGeometry(QtCore.QRect(130, 140, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.theta_o.setFont(font)
        self.theta_o.setStyleSheet("")
        self.theta_o.setAlignment(QtCore.Qt.AlignCenter)
        self.theta_o.setMaximum(90.0)
        self.theta_o.setProperty("value", 61.3)
        self.theta_o.setObjectName("theta_o")
        self.N_o = QtWidgets.QDoubleSpinBox(self.groupBox_2)
        self.N_o.setGeometry(QtCore.QRect(130, 60, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.N_o.setFont(font)
        self.N_o.setAlignment(QtCore.Qt.AlignCenter)
        self.N_o.setDecimals(0)
        self.N_o.setMaximum(2000.0)
        self.N_o.setProperty("value", 1702.0)
        self.N_o.setObjectName("N_o")
        self.label_45 = QtWidgets.QLabel(self.groupBox_2)
        self.label_45.setGeometry(QtCore.QRect(220, 60, 41, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_44 = QtWidgets.QLabel(self.groupBox_2)
        self.label_44.setGeometry(QtCore.QRect(220, 100, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.label_43 = QtWidgets.QLabel(self.groupBox_2)
        self.label_43.setGeometry(QtCore.QRect(220, 140, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.label_48 = QtWidgets.QLabel(self.groupBox_2)
        self.label_48.setGeometry(QtCore.QRect(40, 60, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_46 = QtWidgets.QLabel(self.groupBox_2)
        self.label_46.setGeometry(QtCore.QRect(40, 100, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.label_47 = QtWidgets.QLabel(self.groupBox_2)
        self.label_47.setGeometry(QtCore.QRect(40, 140, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.rg_D2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.rg_D2.setGeometry(QtCore.QRect(33, 271, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rg_D2.setFont(font)
        self.rg_D2.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.rg_D2.setAlignment(QtCore.Qt.AlignCenter)
        self.rg_D2.setReadOnly(True)
        self.rg_D2.setClearButtonEnabled(False)
        self.rg_D2.setObjectName("rg_D2")
        self.rg_D3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.rg_D3.setGeometry(QtCore.QRect(33, 320, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rg_D3.setFont(font)
        self.rg_D3.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.rg_D3.setAlignment(QtCore.Qt.AlignCenter)
        self.rg_D3.setReadOnly(True)
        self.rg_D3.setClearButtonEnabled(False)
        self.rg_D3.setObjectName("rg_D3")
        self.rg_D4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.rg_D4.setGeometry(QtCore.QRect(33, 370, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rg_D4.setFont(font)
        self.rg_D4.setStyleSheet("background-color: rgb(85, 255, 255);")
        self.rg_D4.setAlignment(QtCore.Qt.AlignCenter)
        self.rg_D4.setReadOnly(True)
        self.rg_D4.setClearButtonEnabled(False)
        self.rg_D4.setObjectName("rg_D4")
        self.rg_beta3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.rg_beta3.setGeometry(QtCore.QRect(210, 320, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rg_beta3.setFont(font)
        self.rg_beta3.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.rg_beta3.setAlignment(QtCore.Qt.AlignCenter)
        self.rg_beta3.setReadOnly(True)
        self.rg_beta3.setClearButtonEnabled(False)
        self.rg_beta3.setObjectName("rg_beta3")
        self.rg_beta4 = QtWidgets.QLineEdit(self.groupBox_2)
        self.rg_beta4.setGeometry(QtCore.QRect(210, 370, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rg_beta4.setFont(font)
        self.rg_beta4.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.rg_beta4.setAlignment(QtCore.Qt.AlignCenter)
        self.rg_beta4.setReadOnly(True)
        self.rg_beta4.setClearButtonEnabled(False)
        self.rg_beta4.setObjectName("rg_beta4")
        self.rg_beta2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.rg_beta2.setGeometry(QtCore.QRect(210, 271, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.rg_beta2.setFont(font)
        self.rg_beta2.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.rg_beta2.setAlignment(QtCore.Qt.AlignCenter)
        self.rg_beta2.setReadOnly(True)
        self.rg_beta2.setClearButtonEnabled(False)
        self.rg_beta2.setObjectName("rg_beta2")
        self.frame = QtWidgets.QFrame(self.groupBox_2)
        self.frame.setGeometry(QtCore.QRect(220, 400, 101, 91))
        self.frame.setStyleSheet("image: url(:/logo/avatar.png);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.be3_be2 = QtWidgets.QLineEdit(self.groupBox_2)
        self.be3_be2.setGeometry(QtCore.QRect(70, 420, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.be3_be2.setFont(font)
        self.be3_be2.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.be3_be2.setAlignment(QtCore.Qt.AlignCenter)
        self.be3_be2.setReadOnly(True)
        self.be3_be2.setClearButtonEnabled(False)
        self.be3_be2.setObjectName("be3_be2")
        self.be4_be3 = QtWidgets.QLineEdit(self.groupBox_2)
        self.be4_be3.setGeometry(QtCore.QRect(70, 470, 81, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.be4_be3.setFont(font)
        self.be4_be3.setStyleSheet("background-color: rgb(255, 255, 127);")
        self.be4_be3.setAlignment(QtCore.Qt.AlignCenter)
        self.be4_be3.setReadOnly(True)
        self.be4_be3.setClearButtonEnabled(False)
        self.be4_be3.setObjectName("be4_be3")
        self.label_51 = QtWidgets.QLabel(self.groupBox_2)
        self.label_51.setGeometry(QtCore.QRect(10, 420, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_52 = QtWidgets.QLabel(self.groupBox_2)
        self.label_52.setGeometry(QtCore.QRect(10, 470, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_53 = QtWidgets.QLabel(self.groupBox_2)
        self.label_53.setGeometry(QtCore.QRect(160, 420, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.groupBox_2)
        self.label_54.setGeometry(QtCore.QRect(160, 470, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.groupBox_5 = QtWidgets.QGroupBox(Dispersion)
        self.groupBox_5.setGeometry(QtCore.QRect(20, 30, 371, 80))
        self.groupBox_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.groupBox_5.setObjectName("groupBox_5")
        self.lamda = QtWidgets.QDoubleSpinBox(self.groupBox_5)
        self.lamda.setGeometry(QtCore.QRect(127, 43, 71, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lamda.setFont(font)
        self.lamda.setAlignment(QtCore.Qt.AlignCenter)
        self.lamda.setDecimals(1)
        self.lamda.setMinimum(100.0)
        self.lamda.setMaximum(3000.0)
        self.lamda.setProperty("value", 1030.0)
        self.lamda.setObjectName("lamda")
        self.label_49 = QtWidgets.QLabel(self.groupBox_5)
        self.label_49.setGeometry(QtCore.QRect(102, 46, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_50 = QtWidgets.QLabel(self.groupBox_5)
        self.label_50.setGeometry(QtCore.QRect(210, 40, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.groupBox_2.raise_()
        self.groupBox.raise_()
        self.groupBox_5.raise_()

        self.retranslateUi(Dispersion)
        QtCore.QMetaObject.connectSlotsByName(Dispersion)

    def retranslateUi(self, Dispersion):
        _translate = QtCore.QCoreApplication.translate
        Dispersion.setWindowTitle(_translate("Dispersion", "色散程序"))
        self.groupBox.setTitle(_translate("Dispersion", "啁啾布拉格光栅色散计算转换"))
        self.label.setText(_translate("Dispersion", "<html><head/><body><p><span style=\" font-size:11pt;\">β</span><span style=\" font-size:11pt; vertical-align:sub;\">2</span></p></body></html>"))
        self.label_3.setText(_translate("Dispersion", "<html><head/><body><p><span style=\" font-size:11pt;\">β</span><span style=\" font-size:11pt; vertical-align:sub;\">4</span></p></body></html>"))
        self.label_2.setText(_translate("Dispersion", "<html><head/><body><p><span style=\" font-size:11pt;\">β</span><span style=\" font-size:11pt; vertical-align:sub;\">3</span></p></body></html>"))
        self.groupBox_3.setTitle(_translate("Dispersion", "β -> D"))
        self.label_4.setText(_translate("Dispersion", "ps2"))
        self.label_5.setText(_translate("Dispersion", "ps3"))
        self.label_6.setText(_translate("Dispersion", "ps4"))
        self.label_7.setText(_translate("Dispersion", "D2"))
        self.label_8.setText(_translate("Dispersion", "D3"))
        self.label_9.setText(_translate("Dispersion", "D4"))
        self.label_30.setText(_translate("Dispersion", "ps/nm"))
        self.label_28.setText(_translate("Dispersion", "ps/nm3"))
        self.label_29.setText(_translate("Dispersion", "ps/nm2"))
        self.btod.setText(_translate("Dispersion", "转换"))
        self.r_D2.setText(_translate("Dispersion", "-33.7760"))
        self.r_D3.setText(_translate("Dispersion", "-0.1103"))
        self.r_D4.setText(_translate("Dispersion", "0.0036"))
        self.groupBox_4.setTitle(_translate("Dispersion", "D -> β"))
        self.label_18.setText(_translate("Dispersion", "D2"))
        self.label_16.setText(_translate("Dispersion", "D3"))
        self.label_17.setText(_translate("Dispersion", "D2"))
        self.label_21.setText(_translate("Dispersion", "<html><head/><body><p><span style=\" font-size:11pt;\">β</span><span style=\" font-size:11pt; vertical-align:sub;\">4</span></p></body></html>"))
        self.label_19.setText(_translate("Dispersion", "<html><head/><body><p><span style=\" font-size:11pt;\">β</span><span style=\" font-size:11pt; vertical-align:sub;\">3</span></p></body></html>"))
        self.label_20.setText(_translate("Dispersion", "<html><head/><body><p><span style=\" font-size:11pt;\">β</span><span style=\" font-size:11pt; vertical-align:sub;\">2</span></p></body></html>"))
        self.label_24.setText(_translate("Dispersion", "ps2"))
        self.label_23.setText(_translate("Dispersion", "ps3"))
        self.label_22.setText(_translate("Dispersion", "ps4"))
        self.label_25.setText(_translate("Dispersion", "ps/nm"))
        self.label_26.setText(_translate("Dispersion", "ps/nm2"))
        self.label_27.setText(_translate("Dispersion", "ps/nm3"))
        self.dtob.setText(_translate("Dispersion", "转换"))
        self.r_beta4.setText(_translate("Dispersion", "0.0009"))
        self.r_beta3.setText(_translate("Dispersion", "-0.1217"))
        self.r_beta2.setText(_translate("Dispersion", "18.9955"))
        self.groupBox_2.setTitle(_translate("Dispersion", "光栅对色散量计算"))
        self.label_36.setText(_translate("Dispersion", "ps/nm"))
        self.label_34.setText(_translate("Dispersion", "ps/nm2"))
        self.label_31.setText(_translate("Dispersion", "ps/nm3"))
        self.label_35.setText(_translate("Dispersion", "D2"))
        self.label_33.setText(_translate("Dispersion", "D4"))
        self.label_32.setText(_translate("Dispersion", "D3"))
        self.label_37.setText(_translate("Dispersion", "<html><head/><body><p><span style=\" font-size:11pt;\">β</span><span style=\" font-size:11pt; vertical-align:sub;\">4</span></p></body></html>"))
        self.label_38.setText(_translate("Dispersion", "ps3"))
        self.label_39.setText(_translate("Dispersion", "<html><head/><body><p><span style=\" font-size:11pt;\">β</span><span style=\" font-size:11pt; vertical-align:sub;\">3</span></p></body></html>"))
        self.label_40.setText(_translate("Dispersion", "<html><head/><body><p><span style=\" font-size:11pt;\">β</span><span style=\" font-size:11pt; vertical-align:sub;\">2</span></p></body></html>"))
        self.label_41.setText(_translate("Dispersion", "ps2"))
        self.label_42.setText(_translate("Dispersion", "ps4"))
        self.gcal.setText(_translate("Dispersion", "计算"))
        self.label_45.setText(_translate("Dispersion", "l/mm"))
        self.label_44.setText(_translate("Dispersion", "m"))
        self.label_43.setText(_translate("Dispersion", "°"))
        self.label_48.setText(_translate("Dispersion", "刻线密度："))
        self.label_46.setText(_translate("Dispersion", "垂直距离："))
        self.label_47.setText(_translate("Dispersion", "入射角度："))
        self.rg_D2.setText(_translate("Dispersion", "54.9063"))
        self.rg_D3.setText(_translate("Dispersion", "1.1082"))
        self.rg_D4.setText(_translate("Dispersion", "0.0320"))
        self.rg_beta3.setText(_translate("Dispersion", "0.3848"))
        self.rg_beta4.setText(_translate("Dispersion", "-0.0069"))
        self.rg_beta2.setText(_translate("Dispersion", "-30.9027"))
        self.be3_be2.setText(_translate("Dispersion", "-12.4531"))
        self.be4_be3.setText(_translate("Dispersion", "-17.9641"))
        self.label_51.setText(_translate("Dispersion", "<html><head/><body><p><span style=\" font-size:11pt;\">β</span><span style=\" font-size:11pt; vertical-align:sub;\">3</span><span style=\" font-size:11pt;\">/β</span><span style=\" font-size:11pt; vertical-align:sub;\">2</span></p></body></html>"))
        self.label_52.setText(_translate("Dispersion", "<html><head/><body><p><span style=\" font-size:11pt;\">β</span><span style=\" font-size:11pt; vertical-align:sub;\">4</span><span style=\" font-size:11pt;\">/β</span><span style=\" font-size:11pt; vertical-align:sub;\">3</span></p></body></html>"))
        self.label_53.setText(_translate("Dispersion", "<html><head/><body><p>fs</p></body></html>"))
        self.label_54.setText(_translate("Dispersion", "<html><head/><body><p>fs</p></body></html>"))
        self.groupBox_5.setTitle(_translate("Dispersion", "主要参数设置"))
        self.label_49.setText(_translate("Dispersion", "<html><head/><body><p>λ</p></body></html>"))
        self.label_50.setText(_translate("Dispersion", "nm"))

